### ISSUE TITLE
Fix 404 error crashing server

### ISSUE THREAD

**Issue by killingsworth-kristen** [killingsworth-kristen/killingsworth-kid-backend#1]
Error [ERR_HTTP_HEADERS_SENT]: Cannot set headers after they are sent to the client
    at new NodeError (node:internal/errors:400:5)
    at ServerResponse.setHeader (node:_http_outgoing:663:11)
    at ServerResponse.header (D:\code\killingsworth-kid-backend\node_modules\express\lib\response.js:794:10)
    at ServerResponse.send (D:\code\killingsworth-kid-backend\node_modules\express\lib\response.js:174:12)
    at ServerResponse.json (D:\code\killingsworth-kid-backend\node_modules\express\lib\response.js:278:15)
    at D:\code\killingsworth-kid-backend\routes\UserRoutes.js:24:17
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5) {
  code: 'ERR_HTTP_HEADERS_SENT'
}
node:internal/errors:491
    ErrorCaptureStackTrace(err);
    ^

Error [ERR_HTTP_HEADERS_SENT]: Cannot set headers after they are sent to the client
    at new NodeError (node:internal/errors:400:5)
    at ServerResponse.setHeader (node:_http_outgoing:663:11)
    at ServerResponse.header (D:\code\killingsworth-kid-backend\node_modules\express\lib\response.js:794:10)
    at ServerResponse.send (D:\code\killingsworth-kid-backend\node_modules\express\lib\response.js:174:12)
    at ServerResponse.json (D:\code\killingsworth-kid-backend\node_modules\express\lib\response.js:278:15)
    at D:\code\killingsworth-kid-backend\routes\UserRoutes.js:27:29
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5) {
  code: 'ERR_HTTP_HEADERS_SENT'
}

Node.js v18.13.0
[nodemon] app crashed - waiting for file changes before starting...

**Comment by killingsworth-kristen** [comment]
moved res.status(200).json(obj) into an else statement to prevent from reaching finished state
